name: GitHub Pages (No Manual Deploy)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload site output
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Make sure this is the folder with index.html, style.css, script.js, etc.

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
