name: GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Pages
        uses: actions/configure-pages@v3

      - name: Upload site content
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Replace this with the output folder if you build files into /dist or /build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
